name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: yuasabe/gitleaks-action@patch-1
      with:
        config-path: .github/workflows/config/.gitleaks.toml
