name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: fnxpt/gitleaks-action@remote-rules-with-fix
      with:
        config-path: https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
